- src/DSE.Open.Values/UriAsciiPath.cs
- src/DSE.Open.Values/UriPath.cs
- test/DSE.Open.Values.Tests/UriAsciiPathTests.cs
- test/DSE.Open.Values.Tests/UriPathTests.cs
> Add ToAbsolutePath on UriPath types

- src/DSE.Open.Values/Identifier.cs
- src/DSE.Open.Values/Tag.cs
- src/DSE.Open/Base62Converter.cs
- src/DSE.Open/DecimalExtensions.cs
- src/DSE.Open/DoubleExtensions.cs
- src/DSE.Open/MemoryQueryExtensions.cs
- src/DSE.Open/SingleExtensions.cs
Runtime has now removed all uses.
> Remove manual aggressive inlining

- src/DSE.Open/Collections/Generic/ReadOnlyValueCollection.cs
- src/DSE.Open/Collections/Generic/ReadOnlyValueCollection{T}.cs
- src/DSE.Open/Collections/Generic/ReadOnlyValueSet.cs
- src/DSE.Open/Collections/Generic/ReadOnlyValueSet{T}.cs
> Add CollectionBuilder for ReadOnlyValueSet<T>

- src/DSE.Open.Globalization/CountryCode.cs
- src/DSE.Open.Globalization/CountryCode3.cs
- src/DSE.Open.Globalization/LanguageCode2.cs
- src/DSE.Open.Globalization/gen/net8.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/CountryCode.g.cs
- src/DSE.Open.Globalization/gen/net8.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/CountryCode3.g.cs
- src/DSE.Open.Globalization/gen/net8.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/LanguageCode2.g.cs
- src/DSE.Open/AsciiChar.cs
- src/DSE.Open/AsciiChar2.cs
- src/DSE.Open/AsciiChar3.cs
- src/DSE.Open/Text/Json/Serialization/JsonStringAsciiCharNConverter.cs
This hooks up the various AsciiChars and thereby types that are convertible to them. Also adds a JsonConverter for the various AsciiChars incase we use them directly (we do in one place currently)
> Implement UTF8 json conversion for some more types

- src/DSE.Open.Globalization/LanguageTag.cs
- src/DSE.Open/AsciiString.cs
Uses AsciiString's TryFormat to handle upper and lowercase.
> Tidy LanguageTag slightly

- src/DSE.Open/Text/Json/JsonSharedOptions.cs
- src/DSE.Open/Text/Json/Serialization/JsonBinarySerializer.cs
- test/DSE.Open.Tests/Text/Json/Serialization/JsonBinarySerializerTests.cs
> Fix and test JsonBinarySerializer

- src/DSE.Open/FormattableExtensions.cs
- src/DSE.Open/SpanFormattableExtensions.cs
Probably not a great thing to be boxing 😄
> Fix boxing of IFormattable and ISpanFormattable types in extensions

- DSE.Open.sln
- src/DSE.Open.Abstractions/PaginationOptions.cs
- src/DSE.Open.Results/Pagination.cs
- test/DSE.Open.Abstractions.Tests/DSE.Open.Abstractions.Tests.csproj
- test/DSE.Open.Abstractions.Tests/PaginationOptionsTests.cs
- test/DSE.Open.Abstractions.Tests/xunit.runner.json
It wasn't clear whether it was zero or one-based, so I've documented and added tests.
> Document and test PaginationOptions

- benchmarks/DSE.Open.Benchmarks/Text/StringHelperJoinStringBenchmarks.cs
- src/DSE.Open/Text/StringHelper.Join.cs
- test/DSE.Open.Tests/Text/StringHelperTests.Join.cs
> Re-order StringHelper.Join paramteters

- src/DSE.Open/MemoryExtensions.AsciiChar.cs
- src/DSE.Open/MemoryExtensions.Byte.cs
- src/DSE.Open/MemoryExtensions.Char.cs
- src/DSE.Open/MemoryExtensions.cs
- test/DSE.Open.Tests/MemoryExtensionsTests.cs
Extracts common methods into a two core functions.
> Refactor MemoryExtensions to reduce duplication

- src/DSE.Open/Collections/Concurrent/ConcurrentSet.cs
- src/DSE.Open/Collections/Generic/CollectionExtensions.cs
- src/DSE.Open/Collections/Generic/ReadOnlyKeyedValueCollection.cs
- src/DSE.Open/Collections/ObjectModel/ObservableList.cs
- src/DSE.Open/FormattableExtensions.cs
- src/DSE.Open/SpanFormattableExtensions.cs
Only done in DSE.Open project.
> Change some checks back to Guard.IsNotNull to avoid possible boxing

- test/DSE.Open.Sessions.Tests/SessionContextSerializerTests.cs
> Extend tests for SessionContextSerializer

- gen/DSE.Open.Values.Generators/Extensions/MethodDeclarationSyntaxExtensions.cs
- src/DSE.Open.Records.Abstractions/EthnicityCode.cs
- test/DSE.Open.Records.Abstractions.Tests/EthnicityCodeTests.cs
> Add EthnicityCode to DSE.Open.Records.Abstractions

- src/DSE.Open.Observations/ObservationSnapshot.cs
- test/DSE.Open.Observations.Tests/ObservationSnapshotSetTests.cs
- test/DSE.Open.Observations.Tests/ObservationSnapshotTests.cs
> Extend test coverage of ObservationSnapshots

- gen/DSE.Open.Values.Generators/Model/ValueTypeSpec.cs
- gen/DSE.Open.Values.Generators/ValueTypesGenerator.Emitter.cs
- gen/DSE.Open.Values.Generators/ValueTypesGenerator.cs
- src/DSE.Open.Values.Abstractions/ValueAttribute.cs
Adds an option to not emit implicit downcasts for values.
> Add option to attribute to not emit implicit downcasts for values

- gen/DSE.Open.Localization.Generators/DSE.Open.Localization.Generators.csproj
> Set IncludeBuildOutput false in Localization.Generators

- test/DSE.Open.DomainModel.Tests/Events/DomainBackgroundEventHandlerFake.cs
- test/DSE.Open.DomainModel.Tests/Events/DomainEventHandlerFake.cs
- test/DSE.Open.DomainModel.Tests/Events/TestState.cs
> Make DomainEventDispatcherTests TestState thread-safe

- gen/DSE.Open.Localization.Generators/Resources/Parsing/ResourceItem.cs
> Override equality of ResourceItem

- test/DSE.Open.Language.Abstractions.Tests/SignTests.cs
- test/DSE.Open.Language.Abstractions.Tests/WordTests.cs
- test/DSE.Open.Language.Annotations.Tests/TokenTests.cs
- test/DSE.Open.Tests/Text/StringHelperTests.Join.cs
Closes https://github.com/dseinternational/open-dotnet/issues/211
> Reenable tests using Assert.Equivalent with ByRefLike properties

- src/DSE.Open.Numerics/CategoricalVector.cs
- src/DSE.Open.Numerics/IVector.cs
- src/DSE.Open.Numerics/NumericVector.T.cs
- src/DSE.Open.Numerics/ReadOnlyCategoricalVector.cs
- src/DSE.Open.Numerics/ReadOnlyNumericVector.T.cs
- src/DSE.Open.Numerics/ReadOnlyVector.cs
- src/DSE.Open.Numerics/Serialization/ReadOnlyVectorJsonConverter.cs
- src/DSE.Open.Numerics/Vector.T.cs
- src/DSE.Open.Numerics/Vector.cs
- src/DSE.Open.Numerics/VectorExtensions.cs
- test/DSE.Open.Numerics.Tests/CategorialVectorTests.cs
- test/DSE.Open.Numerics.Tests/NumericVectorTests.cs
- test/DSE.Open.Numerics.Tests/ReadOnlyNumericVectorTests.cs
- test/DSE.Open.Numerics.Tests/ReadOnlyVectorTests.cs
Closes https://github.com/dseinternational/open-dotnet/issues/242
> Support deserialization into readonly vector types

- test/DSE.Open.Numerics.Tests/SeriesTests.cs
- test/DSE.Open.Numerics.Tests/VectorTests.cs
> Add tests to assert vector and series slice doesn't copy
