dseinternational/open-dotnet

benchmarks/DSE.Open.Benchmarks/DSE.Open.Benchmarks.csproj
benchmarks/DSE.Open.Benchmarks/Globalization/LanguageTagTryFormatBenchmarks.cs
gen/DSE.Open.Values.Generators/ValueTypesGenerator.Emitter.cs
gen/DSE.Open.Values.Generators/ValueTypesGenerator.cs
src/DSE.Open.Globalization/LanguageTag.cs
src/DSE.Open.Globalization/gen/net7.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/LanguageTag.g.cs
test/DSE.Open.Globalization.Tests/LanguageTagTests.cs
test/DSE.Open.Values.Generators.Tests/NominalValueTypeGenerationTests.cs

Normalizing LanguageTag output as per recommendation is approx. 80% slower than simply outputting what we were initialized with.
```c#
public class LanguageTagTryFormatBenchmarks
{
private static readonly LanguageTag[] s_tags = new[]
{
LanguageTag.EnglishAustralia,
LanguageTag.EnglishCanada,
LanguageTag.EnglishUk,
LanguageTag.EnglishUs,
LanguageTag.EnglishIndia,
LanguageTag.EnglishIreland,
LanguageTag.EnglishNewZealand,
LanguageTag.EnglishSouthAfrica,
LanguageTag.Parse("fr-FR"),
LanguageTag.Parse("en-CA-x-ca"),
};
[Benchmark]
public void TryFormatNormalized() => s_tags.ForEach(t =>
{
Span<char> b = stackalloc char[t.Length];
_ = t.TryFormat(b, out var cw, "N".AsSpan(), CultureInfo.InvariantCulture);
});
[Benchmark]
public void TryFormatLowercase() => s_tags.ForEach(t =>
{
Span<char> b = …
```

Support formatting LanguageTag

---

benchmarks/DSE.Open.Benchmarks/Globalization/LanguageTagToStringBenchmarks.cs
benchmarks/DSE.Open.Benchmarks/Text/StringHelperRemovePunctuationBenchmarks.cs
gen/DSE.Open.Values.Generators/ValueTypesGenerator.cs
src/DSE.Open.Globalization/LanguageTag.cs
src/DSE.Open.Globalization/gen/net7.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/LanguageTag.g.cs

This is quite a bit more expensive than unformatted. However, it is likely what is wanted more often than not. Have added `ToStringUnformatted()` for occasions when speed is preferred.
```c#
[MemoryDiagnoser]
public class LanguageTagToStringBenchmarks
{
private static readonly LanguageTag[] s_tags = new[]
{
LanguageTag.EnglishAustralia,
LanguageTag.EnglishCanada,
LanguageTag.EnglishUk,
LanguageTag.EnglishUs,
LanguageTag.EnglishIndia,
LanguageTag.EnglishIreland,
LanguageTag.EnglishNewZealand,
LanguageTag.EnglishSouthAfrica,
LanguageTag.Parse("fr-FR"),
LanguageTag.Parse("en-CA-x-ca"),
};
[Benchmark]
public void ToStringFormatted() => s_tags.ForEach(t =>
{
t.ToString();
});
[Benchmark(Baseline = true)]
public void ToStringUnformatted() => s_tags.ForEach(t =>
{
t.ToStringUnformatted();
}); …
```

Default LanguageTag.ToString() to formatted

---

gen/DSE.Open.Values.Generators/Model/ValueTypeSpec.cs
src/DSE.Open.Globalization/gen/net7.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/CountryCode.g.cs
src/DSE.Open.Globalization/gen/net7.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/CountryCode3.g.cs
src/DSE.Open.Globalization/gen/net7.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/LanguageCode2.g.cs
src/DSE.Open.Globalization/gen/net7.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/LanguageTag.g.cs
src/DSE.Open.Values/UriAsciiPath.cs
src/DSE.Open.Values/UriPath.cs
src/DSE.Open.Values/gen/net7.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/AlphaCode.g.cs
src/DSE.Open.Values/gen/net7.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/AlphaNumericCode.g.cs
src/DSE.Open.Values/gen/net7.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/AsciiPath.g.cs
src/DSE.Open.Values/gen/net7.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/ContainsPattern.g.cs
src/DSE.Open.Values/gen/net7.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/Percent.g.cs
src/DSE.Open.Values/gen/net7.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/Ratio.g.cs
src/DSE.Open.Values/gen/net7.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/UriAsciiPath.g.cs
src/DSE.Open.Values/gen/net7.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/UriPath.g.cs
src/DSE.Open/AsciiString.cs
src/DSE.Open/CharSequence.cs

We decided that a safer approach to exposing internal constructors was to implement `From{Type}` methods on the target struct, and use those. That way the constructors can remain private and tracking use of non-validating constructors it not necessary.
This PR implements
- `CharSequence.FromAsciiString` and `AsciiString.ToCharSequence`
- `UriPath.FromUriAsciiPath` and `UriAsciiPath.ToUriPath`

Change value constructors back to private

---

src/DSE.Open/Diagnostics/DiagnosticCode.cs

Previously, using the operators implicitly converted to string.

Provide equality operators for DiagnosticCodes left and right

---

src/DSE.Open/Collections/Generic/CollectionExtensions.cs

Following on from #21, the static class should be the central place for construction logic (as it performs the various optimisations etc). ToReadOnlyValueCollection should call its methods.

Use new CreateRange in ToReadOnlyValueCollection extension

---

src/DSE.Open.Values/EmailAddress.cs
test/DSE.Open.Values.Tests/EmailAddressTests.cs

> An email address with the following deviations from the RFC:
> 
> - Quoted strings are not supported (e.g. `"john..doe"@example.org` is treated as invalid).
> - Domains must contain one or more periods (e.g. `user@localhost` is treated as invalid).
> - Domain literals are not supported (e.g. `user@[IPv6:2001:db8::1]`).
> - Domains must contain at least one ASCII letter (e.g. `email@123.123.123.123` is treated as invalid).
> - Top-level domains (TLDs) are not validated (e.g. `user@example.web` is treated as valid, although `.web` is not a valid TLD).

Properly establish constraints of `EmailAddress`

---

benchmarks/DSE.Open.Benchmarks/DSE.Open.Benchmarks.csproj
benchmarks/DSE.Open.Benchmarks/Text/Json/UriAsciiPathJsonBenchmarks.cs
src/DSE.Open.Abstractions/IUtf8SpanSerializable.cs
src/DSE.Open.Globalization/LanguageTag.cs
src/DSE.Open.Values/Text/Json/Serialization/JsonUtf8SpanSerializableValueConverter.cs
src/DSE.Open.Values/UriAsciiPath.cs
src/DSE.Open.Web/Routing/UriAsciiPathRouteConstraint.cs
src/DSE.Open/AsciiChar.cs
src/DSE.Open/AsciiString.cs
src/DSE.Open/AsciiStringComparer.cs
src/DSE.Open/Text/Json/Serialization/ByteWritingJsonConverter.cs
src/DSE.Open/Text/Json/Serialization/JsonStringAsciiStringConverter.cs
src/DSE.Open/Text/Json/Serialization/SpanParsableByteWritingJsonConverter.cs
src/DSE.Open/ValuesMarshal.cs
test/DSE.Open.Tests/AsciiCharTests.cs
test/DSE.Open.Tests/AsciiStringTests.cs
test/DSE.Open.Values.Tests/Text/Json/Serialization/JsonStringUriAsciiPathConverterTests.cs
test/DSE.Open.Values.Tests/UriAsciiPathTests.cs

| Method    | Mean     | Error   | StdDev  | Gen0   | Allocated |
|---------- |---------:|--------:|--------:|-------:|----------:|
| RoundTrip | 374.3 ns | 0.50 ns | 0.41 ns | 0.0033 |     256 B |
| RoundTrip PR | 200.4 ns | 0.81 ns | 0.72 ns | 0.0012 |      96 B |
```cs
[MemoryDiagnoser]
public class UriAsciiPathJsonBenchmarks
{
private const string Path = "a/b/c/d/e/f/g/h";
private static readonly UriAsciiPath s_pathValue = UriAsciiPath.Parse(Path);
[Benchmark]
public UriAsciiPath RoundTrip()
{
var json = JsonSerializer.Serialize(s_pathValue);
return JsonSerializer.Deserialize<UriAsciiPath>(json);
}
}
```

Implement IUtf8SpanParsable/Formattable for byte backed types

---

benchmarks/DSE.Open.Benchmarks/DSE.Open.Benchmarks.csproj
benchmarks/DSE.Open.Benchmarks/Values/AsciiStringToLowerBenchmarks.cs
benchmarks/DSE.Open.Benchmarks/Values/AsciiStringToStringLowerBenchmarks.cs
benchmarks/DSE.Open.Benchmarks/Values/AsciiStringTryParseBenchmarks.cs
src/DSE.Open/AsciiString.cs
test/DSE.Open.Tests/AsciiStringTests.cs

Speed up in `Equals` and `EqualsCaseInsensitive` (insensitive benchmarked):
| Method                         | Mean      | Error     | StdDev    | Ratio | Allocated | Alloc Ratio |
|------------------------------- |----------:|----------:|----------:|------:|----------:|------------:|
| EqualsCaseInsensitive_Main     | 83.266 ns | 0.1704 ns | 0.1594 ns |  1.00 |         - |          NA |
| EqualsEqualsCaseInsensitive_PR |  6.558 ns | 0.0124 ns | 0.0104 ns |  0.08 |         - |          NA |
Speed up in `TryParse` (mostly for longer values when vectorization kicks in)
| Method         |     Mean |    Error |   StdDev |   Gen0 | Allocated |
| -------------- | -------: | -------: | -------: | -----: | --------: |
| TryParse_Short | 14.99 ns | 0.057 ns | 0.047 ns | 0.0002 |      32 B |
| …

Various improvements for AsciiString

---

src/DSE.Open.Values/UriAsciiPath.cs

Also has the added bonus that for longer inputs `Span.Count` will be much faster.

Remove box in GetSegmentCount

---

benchmarks/DSE.Open.Benchmarks/Values/BinaryValueFromEncodedBytesBenchmarks.cs
benchmarks/DSE.Open.Benchmarks/Values/BinaryValueFromEncodedCharsBenchmarks.cs
benchmarks/DSE.Open.Benchmarks/Values/BinaryValueFromEncodedStringBenchmarks.cs
benchmarks/DSE.Open.Benchmarks/Values/BinaryValueJsonBenchmarks.cs
benchmarks/DSE.Open.Benchmarks/Values/BinaryValueToBase62Benchmarks.cs
benchmarks/DSE.Open.Benchmarks/Values/BinaryValueToBase64Benchmarks.cs
benchmarks/DSE.Open.Benchmarks/Values/BinaryValueToHexLowerBenchmarks.cs
benchmarks/DSE.Open.Benchmarks/Values/BinaryValueToHexUpperBenchmarks.cs
src/DSE.Open/Base62Converter.cs
src/DSE.Open/BinaryValue.Decoding.cs
src/DSE.Open/BinaryValue.Encoding.cs
src/DSE.Open/BinaryValue.cs
src/DSE.Open/HexConverter.cs
src/DSE.Open/Text/Json/Serialization/JsonStringBinaryValueBase64Converter.cs
test/DSE.Open.Tests/Base62ConverterTests.cs
test/DSE.Open.Tests/BinaryValueTests.cs
test/DSE.Open.Tests/HexConverterTests.cs

Nice speedup and reduction in allocations for JSON round trip.
| Method         |     Mean |   Error |  StdDev | Allocated |
| -------------- | -------: | ------: | ------: | --------: |
| RoundTrip_Main | 200.9 ns | 0.34 ns | 0.32 ns |     240 B |
| RoundTrip_PR   | 158.0 ns | 0.43 ns | 0.36 ns |     112 B |
Deserialize now only allocates the number of bytes needed for the backing store.
| Method      | Mean     | Error    | StdDev   | Allocated |
|------------ |---------:|---------:|---------:|----------:|
| Serialize   | 77.32 ns | 0.204 ns | 0.181 ns |      72 B |
| Deserialize | 75.70 ns | 0.190 ns | 0.178 ns |      40 B |
| Method                |     Mean |    Error |   StdDev | Allocated |
| --------------------- | -------: | -------: | -------: | --------: |
| ToBase64String …

Rework BinaryValue

---

benchmarks/DSE.Open.Benchmarks/Collections/ReadOnlyValueCollectionCreateBenchmarks.cs
benchmarks/DSE.Open.Benchmarks/Collections/ReadOnlyValueSetCreateBenchmarks.cs
codecov.yml
src/DSE.Open/Collections/Generic/ReadOnlyValueCollection.cs
src/DSE.Open/Collections/Generic/ReadOnlyValueCollection{T}.cs
src/DSE.Open/Collections/Generic/ReadOnlyValueSet.cs
src/DSE.Open/Collections/Generic/ReadOnlyValueSet{T}.cs

Not sure I read through what I wrote last time 😟 Oops.
Second commit adds a way for derived types to write directly to the backing store (required for efficient collection builder implementations on their types)
| Method             | Mean      | Error     | StdDev    | Ratio | Allocated | Alloc Ratio |
|------------------- |----------:|----------:|----------:|------:|----------:|------------:|
| Create_IEnumerable | 37.070 ns | 0.1301 ns | 0.1016 ns |  1.00 |     480 B |        1.00 |
| Create_Span        | 67.331 ns | 0.4108 ns | 0.3641 ns |  1.82 |     904 B |        1.88 |
| Create_Unsafe      |  4.246 ns | 0.1152 ns | 0.1078 ns |  0.11 |      24 B |        0.05 |
| Method             | Mean      | Error     | StdDev    | Ratio | Allocated | Alloc Ratio |
|------------------- …

Update current collection builders

---

benchmarks/DSE.Open.Benchmarks/Globalization/LanguageTagTryParseBenchmarks.cs
src/DSE.Open.Globalization/LanguageTag.cs
src/DSE.Open.Globalization/gen/net8.0/System.Text.RegularExpressions.Generator/System.Text.RegularExpressions.Generator.RegexGenerator/RegexGenerator.g.cs

From [the docs](https://learn.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-options#explicit-captures-only)
> By default, capturing groups are defined by the use of parentheses in the regular expression pattern. Named groups are assigned a name or number by the (?<name>subexpression) language option, whereas unnamed groups are accessible by index. In the GroupCollection object, unnamed groups precede named groups.
>
> Grouping constructs are often used only to apply quantifiers to multiple language elements, and the captured substrings are of no interest. For example, if the following regular expression:
We _only_ use the regex for matching (and so never require groups to be captured), and so this is all unnecessary overhead.
Using a set of valid codes designed to …

Enable explicit captures only on language tag regex

---

benchmarks/DSE.Open.Benchmarks/Values/IdentifierToStringBenchmarks.cs
gen/DSE.Open.Values.Generators/Extensions/MethodDeclarationSyntaxExtensions.cs
gen/DSE.Open.Values.Generators/ValueTypesGenerator.Emitter.cs
gen/DSE.Open.Values.Generators/ValueTypesGenerator.cs
src/DSE.Open.Globalization/gen/net8.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/CountryCode.g.cs
src/DSE.Open.Globalization/gen/net8.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/CountryCode3.g.cs
src/DSE.Open.Globalization/gen/net8.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/LanguageCode2.g.cs
src/DSE.Open.Globalization/gen/net8.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/LanguageTag.g.cs
src/DSE.Open.Language.Abstractions/gen/net8.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/SignKnowledge.g.cs
src/DSE.Open.Language.Abstractions/gen/net8.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/SignModality.g.cs
src/DSE.Open.Language.Abstractions/gen/net8.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/TreebankPosTag.g.cs
src/DSE.Open.Language.Abstractions/gen/net8.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/UniversalPosTag.g.cs
src/DSE.Open.Language.Abstractions/gen/net8.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/UniversalSyntacticRelation.g.cs
src/DSE.Open.Language.Abstractions/gen/net8.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/Word.g.cs
src/DSE.Open.Observations.Abstractions/gen/net8.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/YesNo.g.cs
src/DSE.Open.Observations.Abstractions/gen/net8.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/YesNoUnsure.g.cs
src/DSE.Open.Records.Abstractions/gen/net8.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/BiologicalSex.g.cs
src/DSE.Open.Records.Abstractions/gen/net8.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/ClinicalConceptCode.g.cs
src/DSE.Open.Records.Abstractions/gen/net8.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/ConditionDiagnosisCode.g.cs
src/DSE.Open.Records.Abstractions/gen/net8.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/Gender.g.cs
src/DSE.Open.Records.Abstractions/gen/net8.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/HearingDiagnosisCode.g.cs
src/DSE.Open.Values/Identifier.cs
src/DSE.Open.Values/gen/net8.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/AlphaCode.g.cs
src/DSE.Open.Values/gen/net8.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/AlphaNumericCode.g.cs
src/DSE.Open.Values/gen/net8.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/ContainsPattern.g.cs
src/DSE.Open.Values/gen/net8.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/Identifier.g.cs
src/DSE.Open.Values/gen/net8.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/Percent.g.cs
src/DSE.Open.Values/gen/net8.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/Ratio.g.cs
src/DSE.Open.Values/gen/net8.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/UriAsciiPath.g.cs
src/DSE.Open.Values/gen/net8.0/DSE.Open.Values.Generators/DSE.Open.Values.Generators.ValueTypesGenerator/UriPath.g.cs

The source generator was outputting span buffers, etc, which is not efficient when we know the length of the string. Instead, we can write directly into the string using string.Create, which can be implemented in the convertible type's ToString method.
I've added `EnsureInitialised` before calling the base type. This would/should have been done in TryFormat anyway so shouldn't be breaking.
For `Identifier` it's roughly half (because we're doing one write instead of two)
| Method                |     Mean |    Error |   StdDev | Ratio | Allocated | Alloc Ratio |
| --------------------- | -------: | -------: | -------: | ----: | --------: | ----------: |
| ToString_Default_Main | 29.12 ns | 0.051 ns | 0.046 ns |  1.00 |     104 B |        1.00 |
| ToString_Default_PR   | 14.09 ns | 0.029 ns …

Call the convertible types `ToString`

---

src/DSE.Open/AsciiString.cs
test/DSE.Open.Tests/AsciiStringTests.cs

Don't know why this only just occurred to me 😄

Much better `{Starts/Ends}With(ROS<char>)` for AsciiString

---

src/DSE.Open/AsciiString.cs

Rents bytes from the ArrayPool instead of AsciiChars, and uses the MaxByteLength for stackalloc not MaxCharLength.

Clean up AsciiString.TryParse with chars

---

src/DSE.Open.Values/DateMonthOnly.cs

`TimeProvider` returns `DateTimeOffset`s, and accessing its `Date` property constructs a new `DateTime`. This provides a cheaper way to construct a `DateMonthOnly` from a `DateTimeOffset`.

Implement FromDateTimeOffset for DateMonthOnly

---

src/DSE.Open.Values/Tag.cs

This was obsoleted because the conversion from chars to bytes was more expensive, so comparing against ROS<byte> was prefereable. With the Ascii class in NET8 it's now much more efficient, so we can remove the attributes.

Remove obsolete from Tag.{Starts/Ends}With(ROS<char>)

---

src/DSE.Open/IO/StreamExtensions.cs
test/DSE.Open.Tests/IO/StreamExtensionsTests.cs

I'm not sure its actually possible to dispose before completing here, but better safe than sorry.

Ensure StreamReader is disposed after reading string in StreamExtensions

---

src/DSE.Open/AsciiChar.cs
src/DSE.Open/AsciiChar2.cs
src/DSE.Open/AsciiChar3.cs
test/DSE.Open.Tests/AsciiChar2Tests.cs
test/DSE.Open.Tests/AsciiCharTests.cs

`"l"`/`"L"` for lowercase, `"u"`/`"U"` for uppercase, empty for no change, otherwise `FormatException`
Changes 2 and 3 to use the same formatting and cleans up `ToString` methods.

Add formatting options and extend tests for AsciiChar

---

gen/DSE.Open.Values.Generators/ValueTypesGenerator.Emitter.cs

Prior to this change, the `IParsable.TryParse` method for values would call directly into the counterpart in the backing type. However, because values are required to implement ISpanParsable, there is always an available span version to call into.
If `ISpanParsable.TryParse` was overriden, but `IParsable.TryParse` was not, this would lead to divergent implementations. To avoid the need to override _both_ `TryParse` methods, this changes the source generator to assume the common case, that `null` is invalid, and to otherwise call into `ISpanParsable.TryParse`.

Change generated IParsable.TryParse to call into ISpanParsable.TryParse

---

src/DSE.Open.Results/PaginatedCollectionValueAsyncResultBuilder.cs
src/DSE.Open.Results/PaginatedCollectionValueResultBuilder.cs

Otherwise, when command validation flags an issue, the pagination validation throws instead of allowing the notification to flow back to the caller.

Allow Pagination.None when result contains error notifications

---

src/DSE.Open/Collections/Generic/ReadOnlyValueCollection{T}.cs
test/DSE.Open.Tests/Collections/Generic/ReadOnlyValueCollectionTests.cs

This avoids a box on direct enumeration. For iteration through interfaces this still boxes. Not sure if this is worth the extra code? I don't want to return the `List<T>.Enumerator` directly because that's leaking an implementation detail.

Add a struct enumerator for ROVC

---

src/DSE.Open.Values/UriAsciiPath.cs
src/DSE.Open.Values/UriPath.cs

Otherwise `path[..n]`, etc., can throw if the caller doesn't check that it is slicing inside a segment (such that the slice is a valid path) - which is unexpected for an indexer!
Callers can now do
```cs
var slice = path[..n];
if (!UriPath.TryParse(slice, out var segment)
{
// Do some handling
}
// Use value
```

Return inner value type when slicing paths

---

src/DSE.Open.Values/Text/LikePattern.cs
test/DSE.Open.Values.Tests/Text/LikePatternTests.cs

According to the comments:
1. `*` Matches any single character
2. `?` Matches any string of zero or more characters.
3. `[ ]` Matches any single character within the specified range (e.g., using range syntax `[a-f]` or specifying the set `[abcdef]`.
4. `[^...]` Any single character not within the specified set (specified like previous, e.g., `[^a-f]` or set `[^abcdef]`.
There's quite a lot of ambiguity here.
First, (1) and (2) presumably overlap: `*` $\subset$ `?`. 
Second, it is not clear when `?` terminates. Presumably a pattern `?` matches any possible value. `a?` matches any possible value where `value[0] == a` where `value.Length > 0`. The problems arise in cases where a pattern is like `a?c`. Does the `?` match the _whole_ value `abcabc`? I.e., is `?` greedy, or does it terminate on …

Start implementing remaining functionality for LikePattern

---

src/DSE.Open/Collections/Generic/CollectionExtensions.Single.cs
test/DSE.Open.Tests/Collections/Generic/CollectionExtensionsTests.Single.cs

<details>
<summary>SingleOrDefault benchmark results</summary>
```
BenchmarkDotNet v0.14.0, macOS Sonoma 14.6.1 (23G93) [Darwin 23.6.0]
Apple M1 Pro, 1 CPU, 10 logical and 10 physical cores
.NET SDK 8.0.303
[Host]     : .NET 8.0.7 (8.0.724.31311), Arm64 RyuJIT AdvSIMD
DefaultJob : .NET 8.0.7 (8.0.724.31311), Arm64 RyuJIT AdvSIMD
```
| Method                               | Mean      | Error     | StdDev    | Ratio | RatioSD | Allocated | Alloc Ratio |
|------------------------------------- |----------:|----------:|----------:|------:|--------:|----------:|------------:|
| SingleOrDefault_Enumerable_Empty     | 11.105 ns | 0.0407 ns | 0.0380 ns |  0.81 |    0.00 |      40 B |        1.00 |
| SingleOrDefault_IReadOnlyList_Empty  |  1.109 ns | 0.0088 ns | 0.0073 ns |  0.08 |    0.00 | …

Add Single overloads for IReadOnlyList

---

src/DSE.Open.Globalization/LanguageTag.cs
src/DSE.Open.Values/Identifier.cs
src/DSE.Open.Values/Text/Json/Serialization/JsonSpanSerializableValueConverter.cs
src/DSE.Open.Values/Text/Json/Serialization/JsonUtf8SpanSerializableValueConverter.cs
src/DSE.Open.Values/UriAsciiPath.cs
src/DSE.Open/AsciiString.cs
src/DSE.Open/MemoryExtensions.AsciiChar.cs
src/DSE.Open/Security/SecureToken.cs

Codegen is much better when stack allocating fixed sized spans. There are some more but these seemed like the most-used paths.

Avoid some variable length stackallocs

---

src/DSE.Open/Collections/Generic/CollectionExtensions.cs

Otherwise this appears for types like `ReadOnlyValueCollection` and `ReadOnlyValueSet` where we are forced to explicitly implement these interfaces to support serialization and deserialization, and allows users to modify them in unsafe ways.

Check IsReadonly in AddRange and throw NotSupportedException

---

src/DSE.Open.Notifications/NotificationLogger.cs

In many places we do
```cs
if (!result.HasValueAndNoErrorNotifications())
{
foreach (var e in result.Notifications.WhereErrorOrAbove())
{
NotificationLogger.LogError(_logger, e);
}
}
```
which means critical notifications are logged as errors. This allows us now to call `NotificationLogger.Log(Logger, e)` and map that to the equivalent log level.

Add Log overload to NotificationLogger mapping Level to LogLevel

---

src/DSE.Open.Sessions/SessionContext.cs

I went with a record-like style. We _could_ make it a record (it is sealed, so that's not breaking), however we want the count of `StorageTokens` anyway so the default `ToString` wouldn't do what we want.

Override ToString on SessionContext for logging

---

Directory.Packages.props

FluentAssertions changed their [licence](https://github.com/fluentassertions/fluentassertions/blob/4aeb488a49247ac053d4a152bfb839f3f9ac9b94/LICENSE.md) in  8.0.0, requiring payment for non-commercial use. Pin to 7.0.0.

Pin FluentAssertions to version 7.0.0

---

src/DSE.Open.Globalization/LanguageTag.cs

Follows the naming pattern for conversions that return another representation without allocating.

Rename LanguageTag.ToAsciiString to AsAsciiString

---

Directory.Packages.props

Because Rider's test runner is broken.

Pin xUnit.v3 to 1.1.0

---

src/DSE.Open.Observations/Observation.cs
test/DSE.Open.Observations.Tests/ObservationTests.cs

Callers hitting the JSON constructor could pass a DateTimeOffset through with more precision.

Ensure Observation times are truncated to millisecond

---

src/DSE.Open.Numerics/ReadOnlyCategorySetExtensions.cs
src/DSE.Open.Numerics/ReadOnlyDataFrameExtensions.cs
src/DSE.Open.Numerics/ReadOnlySeriesExtensions.cs
src/DSE.Open.Numerics/ReadOnlyValueLabelCollectionExtensions.cs
src/DSE.Open.Numerics/ReadOnlyVectorExtensions.cs
test/DSE.Open.Numerics.Tests/ReadOnlyDataFrameExtensionsTests.cs
test/DSE.Open.Numerics.Tests/ReadOnlySeriesExtensionsTests.cs

This pull request introduces a set of extension methods for read-only collections in the `DSE.Open.Numerics` namespace, enabling operations such as creating mutable copies and type validation. Additionally, unit tests have been added to ensure the correctness of these new methods.
* [`test/DSE.Open.Numerics.Tests/ReadOnlyDataFrameExtensionsTests.cs`](diffhunk://#diff-a8672524351574d5128c2d3605467e3fa0015a8b08db1b94478955a9a28037a4R1-R49): Added tests for the `Expect` method in `ReadOnlyDataFrameExtensions`, covering valid retrieval, missing series, and type mismatch scenarios.
* [`test/DSE.Open.Numerics.Tests/ReadOnlySeriesExtensionsTests.cs`](diffhunk://#diff-f8426bf5013ede9f238b95da9b430f7004644971daa9e1306373089747fd3781R1-R46): Added tests for the `Copied` and `Expect` methods in …

Add Expect and Copied extensions for numerics collections
